[workspace]
resolver = "2"
members = [
    "buffered-client",
    "mutex-buffered-client",
    "serial-client",
    "server"
]

[workspace.dependencies]
tokio = { version = "1.37.0", features = ["full"] }
pprof = "0.13.0"

[profile.bench]
debug = true

